all:
  hosts:
    k8s-vm:
      ansible_host: 192.168.64.3
      ansible_user: vmadmin
      ansible_ssh_private_key_file: /Users/syko/Documents/HF/4.Semester/PMM2/Projekt/id_rsa
      ansible_ssh_private_key_passphrase: ""
      odoo_deployments:
        - name: odoo1
          microk8s_namespace: odoo1
          helm_release_name: odoo
          odoo_chart: bitnami/odoo
          odoo_values:
            replicaCount: 1
            postgresql:
              enabled: true
            externalDatabase:
              enabled: false
            odooUsername: admin
            odooPassword: admin123
            odooEmail: admin@example.com
        - name: odoo2
          microk8s_namespace: odoo2
          helm_release_name: odoo
          odoo_chart: bitnami/odoo
          odoo_values:
            replicaCount: 1
            postgresql:
              enabled: true
            externalDatabase:
              enabled: false
            odooUsername: admin
            odooPassword: admin123
            odooEmail: admin@example.com
        - name: odoo3
          microk8s_namespace: odoo3
          helm_release_name: odoo
          odoo_chart: bitnami/odoo
          odoo_values:
            replicaCount: 1
            postgresql:
              enabled: true
            externalDatabase:
              enabled: false
            odooUsername: admin
            odooPassword: admin123
            odooEmail: admin@example.com
